{% set version = "0.15" %}

package:
  name: otrobopt
  version: {{ version }}

source:
  fn: otrobopt-{{ version }}.tar.gz
  url: https://github.com/openturns/otrobopt/archive/v{{ version }}.tar.gz
  sha256: e8ba1a811f7abf0e1c6aafb8432a1280252d0550ae7a94147cc1df284f53d7c3

build:
  number: 0
  skip: true  # [win and py>=313]
  run_exports:
    - {{ pin_subpackage('otrobopt', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns
    - libcblas
  run:
    - python
    - openturns

test:
  imports:
    - otrobopt

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Robust optimization module

extra:
  recipe-maintainers:
    - jschueller
