{% set version = "0.12" %}

package:
  name: otrobopt
  version: {{ version }}

source:
  fn: otrobopt-{{ version }}.tar.gz
  url: https://github.com/openturns/otrobopt/archive/v{{ version }}.tar.gz
  sha256: c243d1b1d158c6580b6af4e2e0a7c29cfc34777561f6e4b92918d9a46a14fda9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otrobopt', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.21*
  run:
    - python
    - openturns 1.21*

test:
  imports:
    - otrobopt

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Robust optimization module

extra:
  recipe-maintainers:
    - jschueller
