appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tK0K02qs3K52Pz1GUf5S+Bjgq/yNxyna1G3ZpXCZuayjKWhcaxaMOETtqld75VNztjd5yGFvgRP9mrIYLW+zzDqpmqdd3J8keB5VGB5if1gm6sR1Cz4CuDNtkzJfwJ+uzKI9bLBa7OZK+FTMrsZOBpLXz5kmcFiKdmZkJM4DlM3i/p/wA8oqw196uc21eGirkvqKBOS+ocKZyGUrGKxnsVvBj5Duim8Bwugy9A8/Rki0aB3F+pO3SYXvlXgS30d331UGkKVNtXgYkNZRtkwdnTDz3/5tjBPuE5DJNh318SF1lrtB55YXYgRjq+n4i8i6Y/A0SUntEbZAz3kC04CnAWtiIYhv/WDZuRPytKtBLvmyWN5dP32fz1LyLGxS9G3NbV8vuj7WrDWt9hTbphgN/WwfwyXLzk2XF6RmhrLRDDB+fEPsH0EdAVXzzg/d4VSaXII9HTFoygU/o/8zo+X064PM+gpI2ubjVfJMQxopW17U9qgxnuoKzyhvQ9LSZYwiCVchQ/y50iN2jmQQbXjUkcpbpKRjtmLsDRk4LGhe+dy/oqe3828VQ2eAHrX0QHUh8SExYydlek7IhWulLNSI1+fzhS6MLw7bSKjDWHb8jqtRsS+gjwyhAV7koh+FPPsYALjxg42AOG9fTvw22JOMz7XjH2Zu2lmGQT3ADpO1yzc=}
provider:
  win: azure
conda_forge_output_validation: true
